import { ATN } from "antlr4ts/atn/ATN";
import { CharStream } from "antlr4ts/CharStream";
import { Lexer } from "antlr4ts/Lexer";
import { Vocabulary } from "antlr4ts/Vocabulary";
export declare class KojiLexer extends Lexer {
    static readonly OpenBlock1 = 1;
    static readonly CloseBlock1 = 2;
    static readonly OpenBlock2 = 3;
    static readonly CloseBlock2 = 4;
    static readonly OpenBlock3 = 5;
    static readonly CloseBlock3 = 6;
    static readonly OpenBlock4 = 7;
    static readonly CloseBlock4 = 8;
    static readonly OpenBlock5 = 9;
    static readonly CloseBlock5 = 10;
    static readonly OpenInline = 11;
    static readonly CloseInline = 12;
    static readonly OpenInline2 = 13;
    static readonly CloseInline2 = 14;
    static readonly Bar = 15;
    static readonly FuriganaParen = 16;
    static readonly AnnotationParen = 17;
    static readonly Kaeriten = 18;
    static readonly Okurigana = 19;
    static readonly Illegible = 20;
    static readonly BugHole = 21;
    static readonly NonJp = 22;
    static readonly Kanji = 23;
    static readonly Kana = 24;
    static readonly NonJpChar = 25;
    static readonly KanjiChar = 26;
    static readonly Lb = 27;
    static readonly WS = 28;
    static readonly ElemName = 29;
    static readonly Colon = 30;
    static readonly HeaderLb = 31;
    static readonly ID = 32;
    static readonly Class = 33;
    static readonly HEADER = 1;
    static readonly channelNames: string[];
    static readonly modeNames: string[];
    static readonly ruleNames: string[];
    private static readonly _LITERAL_NAMES;
    private static readonly _SYMBOLIC_NAMES;
    static readonly VOCABULARY: Vocabulary;
    readonly vocabulary: Vocabulary;
    constructor(input: CharStream);
    readonly grammarFileName: string;
    readonly ruleNames: string[];
    readonly serializedATN: string;
    readonly channelNames: string[];
    readonly modeNames: string[];
    static readonly _serializedATN: string;
    static __ATN: ATN;
    static readonly _ATN: ATN;
}
